---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Heading
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/path/to/media"
use_front_matter_path: false
file_template: ":filename:"
